/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProcessingIdRouteImport } from './routes/processing.$id'
import { Route as ViewerIndexRouteImport } from './routes/viewer.index'
import { Route as ViewerIdRouteImport } from './routes/viewer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingIdRoute = ProcessingIdRouteImport.update({
  id: '/processing/$id',
  path: '/processing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIndexRoute = ViewerIndexRouteImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIdRoute = ViewerIdRouteImport.update({
  id: '/viewer/$id',
  path: '/viewer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/viewer/$id': typeof ViewerIdRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/viewer/$id': typeof ViewerIdRoute
  '/viewer': typeof ViewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/viewer/$id': typeof ViewerIdRoute
  '/viewer/': typeof ViewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/new'
    | '/projects'
    | '/settings'
    | '/processing/$id'
    | '/viewer/$id'
    | '/viewer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/new'
    | '/projects'
    | '/settings'
    | '/processing/$id'
    | '/viewer/$id'
    | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/new'
    | '/projects'
    | '/settings'
    | '/processing/$id'
    | '/viewer/$id'
    | '/viewer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  ProcessingIdRoute: typeof ProcessingIdRoute
  ViewerIdRoute: typeof ViewerIdRoute
  ViewerIndexRoute: typeof ViewerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$id': {
      id: '/processing/$id'
      path: '/processing/$id'
      fullPath: '/processing/$id'
      preLoaderRoute: typeof ProcessingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/': {
      id: '/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof ViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$id': {
      id: '/viewer/$id'
      path: '/viewer/$id'
      fullPath: '/viewer/$id'
      preLoaderRoute: typeof ViewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  ProcessingIdRoute: ProcessingIdRoute,
  ViewerIdRoute: ViewerIdRoute,
  ViewerIndexRoute: ViewerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
